name: Shell workflow
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout Repo
      uses: actions/checkout@v4
       
    - name: Welcome message
      run: echo "My first github action job"

    - name: list files
      run: ls -ltra

    - name: Executing shell script
      run: |
        chmod +x ascii-script.sh
        ./ascii-script.sh